### ISSUE TITLE
Selling more than maximum number of products

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#24]
The app should forbid someone to continually add a product when it reaches the stock value.

**Comment by Saluki** [comment]
"Forbid" is a rather strong word, because someone with an "user" role shouldn't be blocked from registering a sale just because the manager forgot to update the stocks.

But it could be interesting to show some warning message when the POS/Bar component detects that the stock is going under 0. Thoughts?

**Comment by Cocovich** [comment]
I'd advise you to choose a side on this. Either you decide that the manager is always right and you trust the stock (taking into account that he could sometimes forget to update it, you're right), or you state that even the manager is not trustworthy and you put no boundaries on the user's privileges (by letting him do a little more than what he should and warning him if he does so).
At least, there should be some kind of security check to prevent someone, for instance, to sell 1500x beers, whatever is in stock...

**Comment by Saluki** [comment]
I'll -currently- rather go for the second choice. 

Let's take some example: we're in a bar where someone with an user role registers sales. Unfortunately, the stocks aren't up to date (manager forgot something or could not yet update the stock, can always happen).
If some product quantity reaches null in the stock, it's then impossible for the user to register sales for the given product. Consequently, we then have a loss of data because the user cannot register sales. Every user or manager can make errors but the error should not impact others.

On the other hand, a user could register (too many) bad sales.
- Like you suggested, we could put some MAX_SALE_LIMIT in the POS component.
- Allow the manager to disable "wrong" sales. Could be a good improvement for next big release.

So, for the moment:
- In the POS component: develop an alert system that notifies the user when a product is not available in the stock so that he can alert a manager. This could be implemented by showing an alert ( issue #26 ) or showing a little alert icon under the product tile.
- In the STOCK component: explicitly show to the administrator/manager that a product is not available in stock by setting a red colour to the product, show an alert, ...
- Find the best way to implement the MAX_SALE_LIMIT in the POS component.

Sounds like a big commit... Putting this for release 0.5, where the last features will be developed.

**Comment by Saluki** [comment]
Also see issue #28 "Disabling specific sale in cash component"

**Comment by Saluki** [comment]
Well, time for some feedback on the features to implement:

**Displaying an alert in the STOCK component**

Done in referenced commit. When the stock for a certain product is empty, a little alert icon is showed next to the product in the product list and in the preview, a text show that the stock is currently empty:

![screenshot from 2015-07-01 22 25 22](https://cloud.githubusercontent.com/assets/2684557/8464191/b04349da-2040-11e5-9686-eebbe1d60e10.png)

A more visible alert on the page would be unnecessary because it can be normal that some products currently have no stock.

**Notify user in POS component**

This will be very difficult to implement for next releases because the POS cannot update the data client-side. For example, if an user A registers sales in the POS component, while a manager B updates the stock for a specific product, the user A could have wrong data for the product quantities. The solution would be to implement some "real-time" mechanism to inform the POS when stocks have been changed.

**Comment by Saluki** [comment]
After last feedback, closing this issue for the next releases.

**Comment by Cocovich** [comment]
The alert is just fine :)
But what about the products that are about to be out of stock ?
It would be equally useful to have a little orange warning icon next to the items that will soon be no more available.
This way, the manager would more easily send commands before the stock reaches zero.
Its range could initially be set manually from 1 to 5 for instance.

**Comment by Saluki** [comment]
Thanks for the enhancement :)
